- name: Pool kursova4semestrtest2
  hosts: staging
  become: true
  tasks:

  - name: stop all docker containers
    shell: docker stop $(docker ps -a -q)
    ignore_errors: true

  - name: remove all docker containers
    shell: docker rm $(docker ps -a -q)
    ignore_errors: true

  - name: Remove image
    docker_image:
      name: bodyasafff/da
      state: absent

  - name: Pull image
    docker_image:
      name: bodyasafff/da

  - name: Start bodyasafff/da
    shell: docker run -d -p 80:5000 bodyasafff/da
 
